name: vero
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.1
  location: ^7.0.0
  latlong2: ^0.9.1
  geocoding: ^3.0.0
  custom_navigation_bar: ^0.8.2
  flutter_map: ^7.0.1
  flutter_map_location_marker: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true